sudo: false

language: node_js
node_js:
  - "6"

cache:
  directories:
    - ./node_modules

branches:
  except:
    - /^v[0-9]/ # dont build tags separately as they are build anyway for the push

install:
  - npm prune
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: npm@blogfoster.com
  api_key:
    secure: "CDHa5EVzBpJrFThO89KnN9LJXfstubPVByO3gcQbF/zUo+nhzPe7S2kuB86reS/F4yK7YA2VyQIOvlAHeB19nwfpQy5sA4MJLZF8Rfl3YSoXpDp2pme1HMl0JMn1bH46A2a9yXPUpmNg1Jpp0ZC18OEwQygkAMoOpkecf0A3ObIPazgDG0CrqN06UIt/VJdtW1hSoa2TPi/FnmFFsFpQWxiPkdYmB+6dgF0wUH4T6RBggY1lj1sHvFVjsFqom4pqi0YevShC1qnrA7sivOw3F7UuoNVkS+tn8V3Ju/4JqG5mVNHzyk7Htxys5IkobP2+IWKM95k3bVuO0u+Jqk6cSQXaR3c6wNMh30DkVOXW+rlmBH7GxSVnrKJibxMcHmstMYZZO/9XpbL4rcww5GDo2EUrjND6wEsq9Sf569za+F+DRQOELhjgFn0y9QtiYSLVI/oNvcfd7Yd48rORsb8ZNmSphlP4ZzcKZAKyAbNbnZY3ktm0kN76oDyfBQRQp59svf4ZwioAFMPYBgEIj3znmBDnESyIp8Aja29WiHLoKQttMAM2gMoxCT/emnrNZNL6VCr8C2QkNDfkI2p4Sto/DmKtWcQDE1w1aK/0Ohf7Umx3Qe8cq/PZv6Mcp95tYIPvOfeWi0kL6rw5Z9IeyNPUsauogUd4KYCSdy2toz3ORoI="
  wait-until-deployed: true
  skip_cleanup: true
  on:
    repo: blogfoster/eslint-config-blogfoster
    branch: master
    condition: $(git describe --exact-match HEAD) # only deploy if the commit is referenced by a tag as well
