sudo: false
dist: trusty
group: travis_latest

language: node_js
node_js:
  - '8'

cache:
  directories:
    - ./node_modules

branches:
  except:
    - /^v[0-9]/ # dont build tags separately as they are build anyway for the push

install:
  - npm prune
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: npm@blogfoster.com
  api_key:
    secure: "g1Vx32YoqqUTbZjGFLoHAygNheRU+rRYDG3fht1ELSFsoBGoCvejnA/3lAZszmHOb4vxsZvBwJYCRXLhdnIZbVLynBJ+ieybzlffBmJlTcf4zohkaEZDAxRl9VuXhRzy9V8cDhz9RVldoYDuCrOVYc4aY+aaw4+UMnbuLj0K3DSS/Eo21NMZa9ZkyHdZ6rvUAMcMX5YzmrtZQpNATpZro/jlW7Nk1XduPSDcFnWtEgVI+5/muoQh5Lyo1WxKlwwqpnWFQwjfG+IE2xrVyYLJLpx3HEdFoTIkrfgvwMWaiXUdb8+hwL3eyyESzPxBj6eurYQ81u4DBUeuEtPxjMd7r3tn0HYqgs0iviAcCS4DApr7HiVNhKWrqGJoXO7kDG3x272DADTbhQnhAM5tZifdZSRvie9DJq8GKes3FERDcCa2H0BtJF09rsbRse6ox++u7xqkK/dIFwm5pMlM3AYH75MbGYSzIO/ldh74wW5ov58OOxsj6Zp15cr6PGasCSEyotjEZo7V/PQ6gvPH3+ZMPUqPyW+okdHFGcZY9g6mrYKHowhfAqmKRSyuFJ/1E4t6R8crH6FUV+O9iJt6fg2vSkuuaAeyaFxQuRSkR/3yUJ3IKGYN2l5npqhIn9CuKzAmu6s32QyTByELeU9GejeisgtoiL64D95L93O4lyFdeKQ="
  wait-until-deployed: true
  skip_cleanup: true
  on:
    repo: blogfoster/eslint-config-blogfoster
    branch: master
    condition: $(git describe --exact-match HEAD) # only deploy if the commit is referenced by a tag as well
